[template]
# Note: unfortunately, "exclude" means exclude from template processing
#       while "ignore" means exclude from inclusion in generated output entirely
#       (in Cargo.toml, by contrast, "exclude" means exclude from publication)
exclude = ["README.md", "justfile"]

[placeholders.author_github_name]
default = "TODO_NOT_PROVIDED_AT_GENERATION"
type = "string"
prompt = "What is the GitHub user name this will be living under."

# [placeholders.author_repo]
# default = "TODO"
# type = "string"
# prompt = "What is the GitHub user name this will be living under."
# choices = [
#         "reindeer",
#         "elf",
#         "abominable snowperson",
#         "santoid",
#         "living coal",
#         "spirit-of-giving",
# ]

####### General Reference: #######

# Builtins:
# - {{authors}}
# - {{project-name}} =~= {{crate_name}}
# - {{crate_type}}
# - {{os-arch}}
# - {{username}}
# - {{within_cargo_project}}
# - {{is_init}}


# ### Original repo to cargo-generate template steps ##
#
# ## commands ##
#
# ```shell
# sd 'eframe_template' '{{crate_name}}' Cargo.toml src/main.rs assets/sw.js
# sd 'eframe template' '{{crate_name | title_case}}' index.html
# sd '(authors = ).*' '${1}["{{authors}}"]' Cargo.toml
# git diff
# ```
#
# ## equivalent to ##
#
# - `Cargo.toml`
#       - Change the `package.name` from `eframe_template` to `your_crate`.
#       - Change the `package.authors`
# - `main.rs`
#       - Change `eframe_template::TemplateApp` to `your_crate::TemplateApp`
# - `index.html`
#       - Change the `<title>eframe template</title>` to `<title>your_crate</title>`. optional.
# - `assets/sw.js`
#       - Change the `'./eframe_template.js'` to `./your_crate.js` (in `filesToCache` array)
#       - Change the `'./eframe_template_bg.wasm'` to `./your_crate_bg.wasm` (in `filesToCache` array)
