# Builtins:
# - {{authors}}
# - {{project-name}} =~= {{crate_name}}
# - {{crate_type}}
# - {{os-arch}}
# - {{username}}
# - {{within_cargo_project}}
# - {{is_init}}

# [placeholders.hypervisor]
# default = "spirit-of-giving"
# type = "string"
# prompt = "Seasonal Mascot for this Day's Project?"
# choices = [
#         "reindeer",
#         "elf",
#         "abominable snowperson",
#         "santoid",
#         "living coal",
#         "spirit-of-giving",
# ]


# Change the name of the crate: Chose a good name for your project, and change the name to it in:
# * `Cargo.toml`
#     * Change the `package.name` from `eframe_template` to `your_crate`.
#     * Change the `package.authors`
# * `main.rs`
#     * Change `eframe_template::TemplateApp` to `your_crate::TemplateApp`
# * `index.html`
#     * Change the `<title>eframe template</title>` to `<title>your_crate</title>`. optional.
# * `assets/sw.js`
#   * Change the `'./eframe_template.js'` to `./your_crate.js` (in `filesToCache` array)
#   * Change the `'./eframe_template_bg.wasm'` to `./your_crate_bg.wasm` (in `filesToCache` array)
